[theme]
primaryColor = "#4169e3"  # Deep Blue
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6"  # Light Grey for secondary background
textColor = "#4169e3"  # Deep Blue text color
font = "sans serif"
